project_id = "mixfzygyqfknoqkgsmsz"

[functions.vehicle-report]
verify_jwt = false

[functions.create-payment]
verify_jwt = false

[functions.check-payment]
verify_jwt = false

[functions.report-access]
verify_jwt = false

[functions.search-plate-preview]
verify_jwt = false

[functions.create-pix-order]
verify_jwt = false

[functions.enrich-paid-report]
verify_jwt = false

[functions.get-report]
verify_jwt = false

[functions.confirm-order-payment]
verify_jwt = false
